### ISSUE TITLE
crash on UpdateClientMapListEntries()

### ISSUE THREAD

**Issue by ChillerDragon** [ChillerDragon/ddnet7#1]
```
[2019-12-13 15:07:52][server]: player has entered the game. ClientID=0 addr=172.20.10.9:49541
[New Thread 0x7ffff4a1e700 (LWP 10168)]
[2019-12-13 15:07:52][sql]: Getting best time done
[Thread 0x7ffff4a1e700 (LWP 10168) exited]
[2019-12-13 15:07:57][server]: ClientID=0 authed (admin)
[2019-12-13 15:07:59][server]: client dropped. cid=0 addr=unknown type 0 reason='Error sending data'
[2019-12-13 15:07:59][game]: kill killer='0:0:ChillerDragon' victim='0:0:ChillerDragon' weapon=-3 special=0

Thread 1 "DDNet-Server" received signal SIGSEGV, Segmentation fault.
0x00005555555a4d31 in CServer::UpdateClientMapListEntries (this=0x7ffff62be010) at /home/chiller/Desktop/git/ddnet7/src/engine/server/server.cpp:898
898					m_aClients[ClientID].m_pMapListEntryToSend = m_aClients[ClientID].m_pMapListEntryToSend->m_pNext;
(gdb) bt
#0  0x00005555555a4d31 in CServer::UpdateClientMapListEntries (this=0x7ffff62be010) at /home/chiller/Desktop/git/ddnet7/src/engine/server/server.cpp:898
#1  0x00005555555a7e84 in CServer::Run (this=0x7ffff62be010) at /home/chiller/Desktop/git/ddnet7/src/engine/server/server.cpp:1537
#2  0x00005555555a9d4d in main (argc=3, argv=0x7fffffffda68) at /home/chiller/Desktop/git/ddnet7/src/engine/server/server.cpp:1991
(gdb) p ClientID
$1 = 0
(gdb) p m_aClients[ClientID]
value of type `CServer::CClient' requires 103832 bytes, which is more than max-value-size
(gdb) p m_aClients[ClientID].m_pMapListEntryToSend->m_pNext
Cannot access memory at address 0x8
(gdb) 
```

Happend while working on /save

**Comment by ChillerDragon** [comment]
Duplicate of https://github.com/ddnet/ddnet7/issues/66
